services:
  app:
    container_name: pos-data-app
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-data-api
    ports:
      - "2026:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - pos-data-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: postgres:15
    container_name: pos-data-db
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: harpos_data
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: root_password
    ports:
      - "5432:5432"
    networks:
      - pos-data-network

networks:
  pos-data-network:

volumes:
  pgsql-data:
